import type { Metadata } from "next";
import { cookies } from 'next/headers';
import { CookieProvider } from './_test/useCookieContext';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get('token')?.value || null;
  
  return (
    <html lang="ko">
      <body>
        <CookieProvider initialToken={token}>{children}</CookieProvider>
      </body>
    </html>
  );
}
